# Generated by Django 6.0.3 on 2026-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appointment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='info@tinytodds.com', max_length=254),
        ),
    ]
