# Generated by Django 6.0.3 on 2026-03-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_email_appointment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='gmail',
        ),
    ]
