# Generated by Django 6.0.3 on 2026-04-18 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order', '-id']},
        ),
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='content',
            name='data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('programs', 'Programs')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
