# Generated by Django 6.0.3 on 2026-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_date_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('programs', 'Programs'), ('contact', 'Contact'), ('settings', 'Settings')], db_index=True, max_length=50),
        ),
    ]
