# Generated by Django 6.0.3 on 2026-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_content_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('page', 'section')},
        ),
    ]
